catalog/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path('^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path('^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^borrowed/$', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    re_path(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")
    iso_code = models.CharField(max_length=4, unique=True)

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    languages = models.ManyToManyField(Language, help_text='Select a languages for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def display_languages(self):
        """Create a string for the Languages. This is required to display languages in Admin."""
        return ', '.join(languages.name for languages in self.languages.all()[:3])

    display_languages.short_description = 'Languages'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('bookinstance-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (("can_edit_authors", "Set author as edited"),)

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '%s, %s' % (self.last_name, self.first_name)

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
# from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.
from django.utils.translation import gettext_lazy as _

from django.forms import ModelForm
from .models import BookInstance


class DateInput(forms.DateInput):
    input_type = "date"


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class RenewBookModelForm(ModelForm):
    def clean_renewal_date(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back', ]
        labels = {'due_back': _('Renewal date'), }
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).'), }
        widgets = {"due_back": DateInput()}

catalog/views.py
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Book, Author, BookInstance, Genre
from django.views import generic, View
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse, reverse_lazy
from catalog.forms import RenewBookForm
from django.contrib.auth.decorators import permission_required, login_required


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_genres = Genre.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    search_word = 'Wise'
    num_books_search_title = Book.objects.filter(title__contains=search_word).count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_books_search_title': num_books_search_title,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


class BookDetailView(generic.DetailView):
    model = Book
    paginate_by = 10

    def book_detail_view(request, primary_key):
        try:
            book = get_object_or_404(Book, pk=primary_key)
        except Book.DoesNotExist:
            raise Http404("Book does not exist")
        return render(request, 'catalog/book_detail.html', context={'book': book})


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

    def get_queryset(self):
        return Author.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


class AuthorDetailView(generic.DetailView):
    model = Author
    paginate_by = 10

    def author_detail_view(request, primary_key):
        try:
            author = get_object_or_404(Author, pk=primary_key)
        except Author.DoesNotExist:
            raise Http404("Author does not exist")
        return render(request, 'catalog/author_detail.html', context={'author': author})


class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission."""
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/11/2023', }
    permission_required = 'catalog.add_author'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.change_author'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("author-delete", kwargs={"pk": self.object.pk})
            )


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    initial = {'language': 'English', }


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}

    <h1>Delete Author: {{ author }}</h1>

    {% if author.book_set.all %}

        <p>You can't delete this author until all their books have been deleted:</p>
        <ul>
            {% for book in author.book_set.all %}
                <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
            {% endfor %}
        </ul>

    {% else %}
        <p>Are you sure you want to delete the author: {{ author }}?</p>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" action="" value="Yes, delete.">
        </form>
    {% endif %}

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Author:  {{ author }}</h1>

    {% comment %}<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>{% endcomment %} <!-- author detail link not yet defined -->
    <p class="text-muted">{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>
    {% comment %}
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>

  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  {% endcomment %}
    <div style="margin-left:20px;margin-top:20px">
        <dl>
            {% for book in author.book_set.all %}
                <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
                <dd>{{book.summary}}</dd>
            {% endfor %}
        </dl>
    </div>
{% endblock %}

{% block sidebar %}
    {{ block.super }}

    {% if perms.catalog.change_author or perms.catalog.delete_author %}
        <hr>
        <ul class="sidebar-nav">
            {% if perms.catalog.change_author %}
                <li><a href="{% url 'author_update' author.id %}">Update author</a></li>
            {% endif %}
            {% if not author.book_set.all and perms.catalog.delete_author %}
                <li><a href="{% url 'author_delete' author.id %}">Delete author</a></li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Create new Author</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}
author_form.html

catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'books' %}">All books</a></li>
              <li><a href="{% url 'authors' %}">All authors</a></li>
                <hr>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                {% endif %}
            </ul>
              {% if user.is_staff %}
                  <hr>
                  <ul class="sidebar-nav">
                      <li>Staff</li>
                      {% if perms.catalog.can_mark_returned %}
                          <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
                      {% endif %}
                  </ul>
                  <hr>
                  <ul class="sidebar-nav">
                      <li>Add Book or Author</li>
                      {% if perms.catalog.can_edit_authors or perms.catalog.can_mark_returned %}
                          <li><a href="{% url 'book_create' %}">Create book</a></li>
                          <li><a href="{% url 'author_create' %}">Create author</a></li>
                      {% endif %}
                  </ul>
              {% endif %}
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
                {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

catalog/templates/catalog/book_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}

    <h1>Delete Books: {{ book }}</h1>

    {% if book.book_set.all %}

        <p>You can't delete this book until all their books have been deleted:</p>
        <ul>
            {% for book in book.book_set.all %}
                <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
            {% endfor %}
        </ul>

    {% else %}
        <p>Are you sure you want to delete the book: {{ book}}?</p>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" action="" value="Yes, delete.">
        </form>
    {% endif %}

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
    <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong>
        {% for language in book.languages.all %}
            {{ language.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr/>
            <p
                    class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>

        {% endfor %}
    </div>
{% endblock %}

{% block sidebar %}
    {{ block.super }}

    {% if perms.catalog.change_book or perms.catalog.delete_book  %}
        <hr>
        <ul class="sidebar-nav">
            {% if perms.catalog.change_author %}
                <li><a href="{% url 'book_update' book.id %}">Update book</a></li>
            {% endif %}
            {% if not book.book_set.all and perms.catalog.delete_book  %}
                <li><a href="{% url 'book_delete' book.id %}">Delete book</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Create new Book</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}
book_form.html

catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                    ({{book.author}})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Renew: {{book_instance.book.title}}</h1>
    <p>Borrower: {{book_instance.borrower}}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{book_instance.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>

            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if user.is_staff %} - {{ bookinst.borrower }}{% endif %}
                    {% if perms.catalog.can_mark_returned %} - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
                    {% endif %}

                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>

            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}
{% block title %}
    <title>Main page</title>
{% endblock %}
{% block content %}
<h1>Local Library Home</h1>

<p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website">tutorial example</a> on the Mozilla Developer Network.</p>
<p>The tutorial demonstrates how to create a Django skeleton website and application, define URL mappings, views (including Generic List and Detail Views), models and templates.</p>


<h2>UML Models</h2>
<p>An UML diagram of the site's Django model structure is shown below. </p>

<div>
{% load static %}
<img src="{% static 'images/local_library_model_uml.png' %}" alt="My image" width="600px">
</div>

<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>

<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Book`s num with 'Wise':</strong> {{ num_books_search_title }}</li>
    <li><mark><strong>You have visited this page </strong> {{ num_visits }} <strong> time{{ num_visits|pluralize }}.</strong></mark></li>
</ul>
{% endblock %}